// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upwgyahmzitqidzcrjrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwd2d5YWhteml0cWlkemNyanJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzYxOTMsImV4cCI6MjA1NzYxMjE5M30.1Nyms8CgQhwdWJV7TLO3qiU-NalanTGdb0WCcTkrBpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);